# Generated by Django 3.2.6 on 2022-04-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
